[package]
name = "wgpu-sandbox"
version = "0.1.0"
authors = ["Ben Phillips <ben.a.phillips@outlook.com>"]
description = "I am learning WGPU and web assembly by exploring features for very broad use cases."
repository = "https://github.com/Jorbon/wgpu-sandbox"
edition = "2024"

[lib]
crate-type = ["rlib"]

[workspace]
members = [".", "wasm-wrapper"]
default-members = ["."]

[profile.release]
strip = true

[dependencies]
wgpu = "28.0.0"
winit = "0.30.12"
glyphon = "0.10.0"
env_logger = "0.11.9"
log = "0.4.29"
pollster = "0.4.0"
image = { version = "0.25.9", default-features = false, features = ["png"] }
num-traits = "0.2.19"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wgpu = { version = "28.0.0", features = ["webgl"] }
wasm-bindgen = "0.2.110"
wasm-bindgen-futures = "0.4.60"
web-sys = { version = "0.3.87", features = ["Document", "Window", "Element", "Performance", "PerformanceTiming"] }
